# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Duong Ngoc Anh
title: Senior Developer
email: anhduong28@live.com
website: www.anhduong28.github.io

# Social links
twitter_username: anhdn9
github_username:  anhduong28
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: anhduong28
linkedin_username: anhduong28
# pinterest_username: jekyll
youtube_username: mranh2895
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Anh and I'm a senior developer. As well as developer I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>JAVA</mark>, <mark>GCP</mark> and <mark>Drinking Coffee</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
